=== BA-OPC/s2opc_board/schemas/s2opc_clientserver_users_config.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="S2OPC_Users" type="S2OPC_UsersType"/>
  <xs:complexType name="UserAuthorizationType">
    <xs:attribute type="xs:boolean" name="read" default="false"/>
    <xs:attribute type="xs:boolean" name="write" default="false"/>
    <xs:attribute type="xs:boolean" name="execute" default="false"/>
    <xs:attribute type="xs:boolean" name="addnode" default="false"/>
  </xs:complexType>
  <xs:complexType name="AnonymousType">
    <xs:sequence>
          <xs:element type="UserAuthorizationType" name="UserAuthorization"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UserPasswordType">
    <xs:sequence>
          <xs:element type="UserAuthorizationType" name="UserAuthorization"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="user" use="required"/>
    <xs:attribute type="xs:string" name="hash" use="required"/>
    <xs:attribute type="xs:string" name="salt" use="required"/>
    <!-- TODO: Add base64 encoding feature (see ticket #1057)
    <xs:attribute type="xs:string" name="base64" use="optional"/>
    -->
  </xs:complexType>
  <xs:complexType name="UserPasswordConfigurationType">
    <xs:sequence>
      <xs:element type="UserPasswordType" name="UserPassword" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="hash_iteration_count" use="required"/>
    <xs:attribute type="xs:string" name="hash_length" use="required"/>
    <xs:attribute type="xs:string" name="salt_length" use="required"/>
  </xs:complexType>
	<xs:complexType name="DefaultCertificateAuthorizationType">
    <xs:attribute type="xs:boolean" name="read" default="false"/>
    <xs:attribute type="xs:boolean" name="write" default="false"/>
    <xs:attribute type="xs:boolean" name="execute" default="false"/>
    <xs:attribute type="xs:boolean" name="addnode" default="false"/>
  </xs:complexType>
	<xs:complexType name="IssuerType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="cert_path" use="required"/>
        <xs:attribute type="xs:string" name="revocation_list_path" use="required"/>
        <xs:attribute type="xs:boolean" name="root" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TrustedIssuersType">
    <xs:sequence>
      <xs:element type="IssuerType" name="TrustedIssuer" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>One or several trusted certificate authorities</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IssuedCertificateType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="required"/>
				<xs:attribute type="xs:boolean" name="read" use="optional"/>
				<xs:attribute type="xs:boolean" name="write" use="optional"/>
				<xs:attribute type="xs:boolean" name="execute" use="optional"/>
				<xs:attribute type="xs:boolean" name="addnode" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IssuedCertificatesType">
    <xs:sequence>
      <xs:element type="IssuedCertificateType" name="IssuedCertificate" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>One or several explicitly trusted certificates issued by provided issuers or self-signed</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UntrustedIssuersType">
    <xs:sequence>
      <xs:element type="IssuerType" name="UntrustedIssuer" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>One or several untrusted certificate authorities. Those are only used to validate trust chain of issued certificate.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UserCertificatesType">
    <xs:sequence>
      <xs:element type="DefaultCertificateAuthorizationType" name="DefaultCertificateAuthorization" />
      <xs:element type="TrustedIssuersType" name="TrustedIssuers" minOccurs="0"/>
      <xs:element type="IssuedCertificatesType" name="IssuedCertificates" minOccurs="0">
        <xs:annotation>
          <xs:documentation>At least one shall be filled in either TrustedIssuers or IssuedCertificates</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="UntrustedIssuersType" name="UntrustedIssuers" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="S2OPC_UsersType">
    <xs:sequence>
      <xs:element type="AnonymousType" name="Anonymous" minOccurs="0"/>
      <xs:element type="UserPasswordConfigurationType" name="UserPasswordConfiguration" minOccurs="0" maxOccurs="1"/>
      <xs:element type="UserCertificatesType" name="UserCertificates" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== BA-OPC/s2opc_board/tests/ClientServer/data/config/S2OPC_UACTT_Users.xml
<?xml version='1.0' encoding='utf-8'?>
<S2OPC_Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_clientserver_users_config.xsd">
  <Anonymous>
    <UserAuthorization write="true" read="true" execute="true" addnode="true" />
  </Anonymous>
  <UserPassword user="user1" pwd="cYgA0qffTvGYn4JFNMtwyy/7xHgG3SNfSyZn2U9e/fU=" salt="cy7PLE59LTnr1vV00OnyVA==" iter="1000000" base64="true">
    <UserAuthorization write="true" read="true" execute="true" addnode="true" />
  </UserPassword>
  <UserPassword user="user2" pwd="fvp1FxTuKFjdnWc08HzdvZYWD0PK2PBhqXD/LH+Od+I=" salt="eatVUCTdclE1OCOk1vpyCw==" iter="1000000" base64="true">
    <UserAuthorization write="true" read="true" execute="true" addnode="true" />
  </UserPassword>
  <UserPassword user="username" pwd="+P1XO5f43/EBzjiKGWI7OqlYQAFtNPjeJqLceCv4r7o=" salt="9yuu5eKolyp4OLS++9tT4g==" iter="1000000" base64="true">
    <!-- user with no right: refused with use access denied -->
    <UserAuthorization/>
  </UserPassword>

</S2OPC_Users>

=== BA-OPC/s2opc_board/samples/ClientServer/data/config/S2OPC_Users_Demo_Config.xml
<?xml version='1.0' encoding='utf-8'?>
<S2OPC_Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_clientserver_users_config.xsd">
  <Anonymous>
    <!-- Anonymous is read only -->
    <UserAuthorization write="false" read="true" execute="false" />
  </Anonymous>
  <UserPasswordConfiguration hash_iteration_count="10000" hash_length="32" salt_length="16">
    <!-- "user1" pwd=password cannot call methods of address space -->
    <UserPassword user="user1" hash="q9UVP2qKV+xvxWlXbHjl//OLy+gBFf5yipvO9uOybIM=" salt="M59HxepygLeEw5sqFJ+Zgw==" base64="true">
      <UserAuthorization write="true" read="true" execute="false" />
    </UserPassword>
    <!-- "me" pwd=1234 has all right accesses.
        note: still restricted by nodes static access rights in address space.
        note: if base64="false" or missing then hex encoding is used
    -->
    <UserPassword user="me" hash="847d892ffaccb9822d417866f9d491389b29134b3c73c3a429ac95c627f9d40a" salt="17faf802f81c2503d3043042e79004b4">
      <UserAuthorization write="true" read="true" execute="true" />
    </UserPassword>
  </UserPasswordConfiguration>
</S2OPC_Users>

=== BA-OPC/s2opc_board/tests/ClientServer/data/config/S2OPC_Test_Users.xml
<?xml version='1.0' encoding='utf-8'?>
<S2OPC_Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_clientserver_users_config.xsd">
  <Anonymous>
    <UserAuthorization/>
  </Anonymous>
  <UserPasswordConfiguration hash_iteration_count="1000000">
    <!-- user="noaccess" pwd="secret" -->
    <UserPassword user="noaccess" hash="acpYCbcva41fgXR5lWu9LAQUAK7SEiNKI2+3hOULASM=" salt="49squ1J2GYW5fIJx3DwNdQ==" base64="true">
      <UserAuthorization/>
    </UserPassword>
    <!-- user="user1" pwd="12345" -->
    <UserPassword user="user1" hash="SEKXuAwH5xlhNmheox0g0tprkxvr1ALl7K3O8n7Zlbc=" salt="x3raGtWgTTrdV00TSOHogw==" base64="true">
      <UserAuthorization write="true" read="false" execute="true" />
    </UserPassword>
    <!-- user="user2" pwd="password2" -->
    <UserPassword user="user2" hash="Xq8N0qmhigKguRlxMbCpDVBGEPZS4tGU1C7NrmiGt1U=" salt="FvOoOKJaLHnmH9FEt78nhg==" base64="true">
      <UserAuthorization write="false" read="true" execute="true" />
    </UserPassword>
    <!-- user="user3" pwd="42" -->
    <UserPassword user="user3" hash="b399cf45e23d609b1d2673eda7890fe501b0075f489271fdb32b3eb161ac7796" salt="eb4730f39ab2ad487fab46a848bae2b2" base64="false">
      <UserAuthorization  write="true" read="true" execute="false" />
    </UserPassword>
  </UserPasswordConfiguration>

</S2OPC_Users>
